/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.BookingControl;
import Model.Hotel;

/**
 * GUI class for jDialog panel for booking a room.
 * @author Sævar Ingi Sigurðsson <sis108@hi.is>
 */
public class BookRoomDialog extends javax.swing.JDialog {

    /**
     * Instance variables.
     */
    Hotel hotelChosen;
    
    /**
     * Creates new form BookHotelDialog
     */
    public BookRoomDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Setter for Hotel text field.
     * @param hotel - String to be placed in text field.
     */
    public void setHotelText(String hotel) {
        this.jHotelText.setText(hotel);
    }
    
    /**
     * Setter for Room text field.
     * @param room - String to be placed in text field.
     */
    public void setRoomText(String room) {
        this.jRoomText.setText(room);
    }
    
    /**
     * Setter for instance variable hotelChosen.
     * @param hotelChosen - the chosen hotel.
     */
    public void setHotelChosen(Hotel hotelChosen) {
        this.hotelChosen = hotelChosen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBookButton = new javax.swing.JButton();
        jTitleLabel = new javax.swing.JLabel();
        jHotelLabel = new javax.swing.JLabel();
        jRoomLabel = new javax.swing.JLabel();
        jChkinLabel = new javax.swing.JLabel();
        jChkoutLabel = new javax.swing.JLabel();
        jLateLabel = new javax.swing.JLabel();
        jKtLabel = new javax.swing.JLabel();
        jKtText = new javax.swing.JTextField();
        jHotelText = new javax.swing.JTextField();
        jRoomText = new javax.swing.JTextField();
        jChkinText = new javax.swing.JTextField();
        jChkoutText = new javax.swing.JTextField();
        jLateComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBookButton.setText("Book Room");
        jBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookButtonActionPerformed(evt);
            }
        });

        jTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitleLabel.setText("Book Room");

        jHotelLabel.setText("Hotel:");

        jRoomLabel.setText("Room No.:");

        jChkinLabel.setText("Check-in:");

        jChkoutLabel.setText("Check-out:");

        jLateLabel.setText("Late Checkout:");

        jKtLabel.setText("Kennitala/SSN:");

        jKtText.setText("Enter SSN");
        jKtText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jKtTextFocusGained(evt);
            }
        });

        jHotelText.setEditable(false);

        jRoomText.setEditable(false);

        jChkinText.setText("Enter Check-in date (YYYY-MM-DD)");
        jChkinText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jChkinTextFocusGained(evt);
            }
        });

        jChkoutText.setText("Enter Check-out date (YYYY-MM-DD)");
        jChkoutText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jChkoutTextFocusGained(evt);
            }
        });

        jLateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKtLabel)
                            .addComponent(jHotelLabel)
                            .addComponent(jRoomLabel)
                            .addComponent(jLateLabel)
                            .addComponent(jChkinLabel)
                            .addComponent(jChkoutLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKtText)
                            .addComponent(jHotelText)
                            .addComponent(jRoomText)
                            .addComponent(jChkinText)
                            .addComponent(jChkoutText, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKtLabel)
                    .addComponent(jKtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHotelLabel)
                    .addComponent(jHotelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRoomLabel)
                    .addComponent(jRoomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkinLabel)
                    .addComponent(jChkinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkoutLabel)
                    .addComponent(jChkoutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLateLabel)
                    .addComponent(jLateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jKtTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jKtTextFocusGained
        jKtText.selectAll();
    }//GEN-LAST:event_jKtTextFocusGained

    private void jChkinTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jChkinTextFocusGained
        jChkinText.selectAll();
    }//GEN-LAST:event_jChkinTextFocusGained

    private void jChkoutTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jChkoutTextFocusGained
        jChkoutText.selectAll();
    }//GEN-LAST:event_jChkoutTextFocusGained

    /**
     * Action handler for "Book Room" button.
     * @param evt - button clicked.
     */
    private void jBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookButtonActionPerformed
        BookingControl bc = new BookingControl();
        
        int bookingId;
        String kt = jKtText.getText();
        int hotel = hotelChosen.getID();
        int room = Integer.parseInt(jRoomText.getText());
        String chkin = jChkinText.getText();
        String chkout = jChkinText.getText();
        Boolean late = true;
        
        if (jLateComboBox.getSelectedItem().equals("No")) {
            late = false;
        }
        
        bc.createSortedBookingIdArray();
        int[] idArray = bc.getBookingIds();
        bookingId = bc.findFirstMissingNumber(idArray, 0, idArray.length - 1);
        
        bc.bookRoom(bookingId, kt, hotel, room, chkin, chkout, late);
        
        this.setVisible(false);
    }//GEN-LAST:event_jBookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRoomDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookRoomDialog dialog = new BookRoomDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBookButton;
    private javax.swing.JLabel jChkinLabel;
    private javax.swing.JTextField jChkinText;
    private javax.swing.JLabel jChkoutLabel;
    private javax.swing.JTextField jChkoutText;
    private javax.swing.JLabel jHotelLabel;
    private javax.swing.JTextField jHotelText;
    private javax.swing.JLabel jKtLabel;
    private javax.swing.JTextField jKtText;
    private javax.swing.JComboBox<String> jLateComboBox;
    private javax.swing.JLabel jLateLabel;
    private javax.swing.JLabel jRoomLabel;
    private javax.swing.JTextField jRoomText;
    private javax.swing.JLabel jTitleLabel;
    // End of variables declaration//GEN-END:variables
}
