/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.HotelControl;
import Control.RoomControl;
import Model.Hotel;
import Model.Room;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 * GUI class for JDialog panel for a list of hotels.
 * @author Sævar Ingi Sigurðsson <sis108@hi.is>
 */
public class HotelListDialog extends javax.swing.JDialog {

    /**
     * Instance variables.
     */
    MainFrame mf = new MainFrame(); // Main window.
    DefaultListModel<String> hotelsModel; // List model.
    ArrayList<Hotel> hotelList; // List of hotels making up list model.
    
    /**
     * Creates new form HotelListDialog
     */
    public HotelListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Create a list model from a list of hotels.
     * @param hotels - ArrayList of hotels.
     */
    public void createHotelsListModel(ArrayList<Hotel> hotels) {
        hotelsModel = new DefaultListModel<>();
        
        for (int i = 0; i < hotels.size(); i++) {
            hotelsModel.addElement("" + hotels.get(i).getID() + " " 
                    + hotels.get(i).getName() + " - Rating : " 
                    + hotels.get(i).getRating()); 
        }
        
        jHotelsList.setModel(hotelsModel);
    }
    
    /**
     * Setter for instance variable hotelList.
     * @param hotelList - ArrayList of hotels.
     */
    public void setHotelList(ArrayList<Hotel> hotelList) {
        this.hotelList = hotelList;
    }
    
    /**
     * Getter for instance variable hotelList.
     * @return 
     */
    public ArrayList<Hotel> getHotelList() {
        return hotelList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCloseButton = new javax.swing.JButton();
        jTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jHotelsList = new javax.swing.JList<>();
        jRoomsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCloseButton.setText("Close");
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButtonActionPerformed(evt);
            }
        });

        jTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitleLabel.setText("Available hotels for your location");

        jScrollPane1.setViewportView(jHotelsList);

        jRoomsButton.setText("Available Rooms");
        jRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoomsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRoomsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCloseButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCloseButton)
                    .addComponent(jRoomsButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action handler for "Close" button.
     * @param evt - button clicked.
     */
    private void jCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jCloseButtonActionPerformed

    /**
     * Action handler for "Available Rooms" button.
     * @param evt - button clicked.
     */
    private void jRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoomsButtonActionPerformed
        RoomControl rc = new RoomControl();
        HotelControl hc = new HotelControl();
        RoomsListDialog rld = new RoomsListDialog(mf, true);
        ArrayList<Room> rooms;
        
        int hotelId = hotelList.get(jHotelsList.getSelectedIndex()).getID();
        
        rooms = rc.getRoomsByHotel(hotelId);
        rld.setTitleText("Rooms available in " + hc.getHotelById(hotelId).getName() 
                + " - " + hc.getHotelById(hotelId).getLocation());
        rld.setHotelChosen(hc.getHotelById(hotelId));
        rld.setRoomsList(rooms);
        rld.createRoomsListModel(rooms);
        
        rld.setVisible(true);
    }//GEN-LAST:event_jRoomsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HotelListDialog dialog = new HotelListDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCloseButton;
    private javax.swing.JList<String> jHotelsList;
    private javax.swing.JButton jRoomsButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitleLabel;
    // End of variables declaration//GEN-END:variables
}
