/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Control.*;
import Model.Booking;
import Model.Hotel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * GUI class for the main frame of the application.
 * @author Sævar Ingi Sigurðsson <sis108@hi.is>
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame.
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButtonBookings = new javax.swing.JButton();
        jTextKt = new javax.swing.JTextField();
        jTextSearch = new javax.swing.JTextField();
        jChkinLabel = new javax.swing.JLabel();
        jChkoutLabel = new javax.swing.JLabel();
        jTextChkin = new javax.swing.JTextField();
        jTextChkout = new javax.swing.JTextField();
        jMinRatLabel = new javax.swing.JLabel();
        jMinRatComboBox = new javax.swing.JComboBox<>();
        jMaxRatLabel = new javax.swing.JLabel();
        jMaxRatComboBox = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBookings.setText("My Bookings");
        jButtonBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookingsActionPerformed(evt);
            }
        });

        jTextKt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextKt.setText("Kennitala");
        jTextKt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextKtFocusGained(evt);
            }
        });

        jTextSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSearch.setText("Where are you going?");
        jTextSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextSearchFocusGained(evt);
            }
        });

        jChkinLabel.setText("Check-in");

        jChkoutLabel.setText("Check-out");

        jTextChkin.setText("2017-01-01");
        jTextChkin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextChkinFocusGained(evt);
            }
        });

        jTextChkout.setText("2017-01-02");
        jTextChkout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextChkoutFocusGained(evt);
            }
        });

        jMinRatLabel.setText("min. Rating");

        jMinRatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jMaxRatLabel.setText("max Rating");

        jMaxRatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jMaxRatComboBox.setSelectedIndex(5);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextChkin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jChkinLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jChkoutLabel)
                                .addComponent(jTextChkout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMinRatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMinRatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMaxRatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMaxRatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextKt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBookings)
                    .addComponent(jTextKt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkinLabel)
                    .addComponent(jChkoutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextChkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextChkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMinRatLabel)
                    .addComponent(jMinRatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMaxRatLabel)
                    .addComponent(jMaxRatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * A few focusGained functions.
     * Select all text in a text field when it gains focus.
     * @param evt 
     */
    private void jTextKtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextKtFocusGained
        jTextKt.selectAll();
    }//GEN-LAST:event_jTextKtFocusGained

    private void jTextSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSearchFocusGained
        jTextSearch.selectAll();
    }//GEN-LAST:event_jTextSearchFocusGained

    private void jTextChkinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextChkinFocusGained
        jTextChkin.selectAll();
    }//GEN-LAST:event_jTextChkinFocusGained

    private void jTextChkoutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextChkoutFocusGained
        jTextChkout.selectAll();
    }//GEN-LAST:event_jTextChkoutFocusGained

    /**
     * Action handler for "My Bookings" button.
     * @param evt - button clicked.
     */
    private void jButtonBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingsActionPerformed
        BookingControl bc = new BookingControl();
        MyBookingsDialog mbd = new MyBookingsDialog(this, true);
        String kt = jTextKt.getText();
        ArrayList<Booking> bookingsByKt = bc.getBookingsByKt(kt);
        
        mbd.setKt(kt);
        mbd.setBookingsList(bookingsByKt);
        mbd.createBookingsListModel(bookingsByKt);
        mbd.setTitleText("Bookings for " + kt);
        
        mbd.setVisible(true);
    }//GEN-LAST:event_jButtonBookingsActionPerformed

    /**
     * Action handler for "Search" button.
     * @param evt - button clicked.
     */
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        HotelListDialog hld = new HotelListDialog(this,true);
        HotelControl hc = new HotelControl();
        ArrayList<Hotel> hotels;
        ArrayList<Hotel> hotelsByRat;
        
        String searchString = jTextSearch.getText();
        String chkinSting = jTextChkin.getText();
        String chkoutString = jTextChkout.getText();
        int minRating = jMinRatComboBox.getSelectedIndex();
        int maxRating = jMaxRatComboBox.getSelectedIndex();
        
        hotels = hc.getHotelByLocation(searchString);
        hotelsByRat = hc.getHotelByRatingRangeFromList(hotels, minRating, maxRating);
        hc.orderByRating(hotelsByRat);
        hld.createHotelsListModel(hotelsByRat);
        hld.setHotelList(hotelsByRat);
        
        hld.setVisible(true);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookings;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jChkinLabel;
    private javax.swing.JLabel jChkoutLabel;
    private javax.swing.JComboBox<String> jMaxRatComboBox;
    private javax.swing.JLabel jMaxRatLabel;
    private javax.swing.JComboBox<String> jMinRatComboBox;
    private javax.swing.JLabel jMinRatLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextChkin;
    private javax.swing.JTextField jTextChkout;
    private javax.swing.JTextField jTextKt;
    private javax.swing.JTextField jTextSearch;
    // End of variables declaration//GEN-END:variables
}
